Repository codestates-seb/seb41_main_026, pull requests merged in 2023-01, with the labels that each got.

#31 모달창 이동 구현
  client/src/components/Modal/ModalFindPassword.jsx
  client/src/components/Modal/ModalLogin.jsx
  client/src/components/Modal/ModalSignUp.jsx
Labels: FE

#63 Refactoring: 헤더, 푸터 공통 컴포넌트 적용 리팩터링(필수 적용)
  client/public/icon-glass.svg
  client/src/App.js
  client/src/components/Common/Footer.jsx
  client/src/components/Common/Header.jsx
  client/src/components/Common/Layout.jsx
  client/src/components/Common/Sample.jsx
  client/src/components/MyPage/MyPageComment.jsx
  client/src/components/MyPage/MyPageInfo.jsx
  client/src/components/MyPage/MyPageLike.jsx
  client/src/components/Search/SearchBody.jsx
  client/src/components/Search/SearchSidebar.jsx
  client/src/components/SeasonSection/SeasonSection.jsx
  client/src/pages/ContentPage/ContentPage.jsx
  client/src/pages/HomePage/MainGuide.jsx
  client/src/pages/HomePage/MainPage.jsx
  client/src/pages/HomePage/MainSearch.jsx
  client/src/pages/HomePage/MainSeason.jsx
  client/src/pages/MyPage/MyPage.jsx
Labels: FE, 👨‍🔧Refactor

#66 FE: 로그인 회원가입 로그아웃 리펙토링
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/API/loginAPI.jsx
  client/src/components/Common/Header.jsx
  client/src/components/Modal/ModalLogin.jsx
  client/src/components/Modal/ModalSignUp.jsx
  client/src/util/alertStore.jsx
  client/src/util/tokenStore.jsx
Labels: FE, 👨‍🔧Refactor

#77 FE: 로그인 회원가입 랜덤 이미지
  client/src/components/Common/Header.jsx
  client/src/components/Modal/ModalLogin.jsx
  client/src/components/Modal/ModalSignUp.jsx
  client/src/redux/userSlice.jsx
Labels: FE, 🌟Feature, 👨‍🔧Refactor

#78 Fe: 검색 페이지 구현
  client/src/components/Common/Header.jsx
  client/src/components/Search/SearchBody.jsx
  client/src/components/Search/SearchSidebar.jsx
  client/src/components/Search/SearchSidebarBody.jsx
  client/src/pages/HomePage/MainSearch.jsx
Labels: FE, 🌟Feature

#107 FE: 로그인 회원가입 에러처리 및 기능 추가
  client/src/components/Modal/ModalLogin.jsx
  client/src/components/Modal/ModalSignUp.jsx
  client/src/components/MyPage/MyPageInfo.jsx
  client/src/util/alertStore.jsx
Labels: FE

#118 FE: 리프레시 토큰 처리 및 토큰 만료 시 처리
  client/src/API/Refresh.jsx
  client/src/API/loginAPI.jsx
  client/src/API/signUpAPI.jsx
  client/src/components/Common/Header.jsx
  client/src/components/Modal/ModalLogin.jsx
  client/src/components/Modal/ModalSignUp.jsx
  client/src/redux/userSlice.jsx
Labels: FE
